#!/bin/sh
IUSER="$1"

if [ -z "$IUSER" ]; then
    IUSER="$USER"
fi

if [ -z "$IUSER" ]; then
    IUSER="root"
    DEST_FOLDER=/root
else
    DEST_FOLDER="/home/$IUSER"
fi

SCRIPT=$(readlink -f "$0")
SOURCE_FOLDER=$(dirname "$SCRIPT")

if [ -z "$(command -v zsh)" ]; then
    echo "Warning: You do not have zsh installed"
    echo "Use package manager to install zsh and use dotfiles zsh part"
fi

install_file() {
    local f="$1"
    local m="$2"
    if [ -z "$m" ]; then
        m='755'
    fi
    local src="$SOURCE_FOLDER/$f"
    local dst="$DEST_FOLDER/$f"
    install -v -m $m $src $dst
}

install_dir() {
    local d="$1"
    local src="$SOURCE_FOLDER/$d"
    local dst="$DEST_FOLDER/$d"
    local ff=""
    install -vd $src $dst
    for f in $src/*; do
        ff=$(echo $f | sed "s#$SOURCE_FOLDER##g")
        if [ -f $f ]; then
            install_file $ff
        elif [ -d $f ]; then
            install_dir $ff
        fi
    done
}

echo "Installing dotfiles"

install_file .zshrc
install_dir .zshrc.d
install_file .vimrc
install_dir .local